### ISSUE TITLE
One big issue for the smaller issues

### ISSUE THREAD

**Issue by ElizabethK9** [ElizabethK9/PriceQuotationApp#1]
- [ ] When the app starts, it should display the Price Quotation page with no subtotal or #2
discount percent, and it should set the discount amount and total to $0.00.
- [ ] If the user enters a valid subtotal and discount percent and clicks the Calculate button, #3
the app should calculate and display the discount amount and total.
- [ ] If the user enters invalid data and clicks the Calculate button, the app should display a #4
summary of validation errors above the form.
- [ ] The sales price is required and must be a valid number that’s greater than 0. #5
- [ ] The discount percent is required and must be a valid number from 0 to 100. #6
- [ ] If the user clicks the Clear link, the app should reset the form to how it was when the app #7
first started.
- [ ] Use the MVC pattern. To do that, create a model class that stores the subtotal and #8
discount percent and calculates the discount amount and total. Make sure to bind that
model to the Razor view that displays the Price Quotation page shown above.
- [ ] Use a Razor layout to store the , , and elements. #9
- [ ] Use a custom CSS style sheet to style the HTML elements so they appear as shown #10
above.
